### ISSUE TITLE
Only Java 12 supported?

### ISSUE THREAD

**Issue by valencik** [DataDog/sketches-java#7]
**Describe what happened:**
Attempting to use this library from a Java 8 JDK results in the following:

```
java.lang.UnsupportedClassVersionError: com/datadoghq/sketch/ddsketch/DDSketch has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 52.0
  java.lang.ClassLoader.defineClass1(Native Method)
  java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
...
```

**Describe what you expected:**
For the library to work on many versions of Java, or for the README to explicitly state the version requirements.

👋 Thanks for creating and sharing this library. Perhaps it needs a newer version of Java, if that's the case, could it be stated in the README?
Cheers!

**Comment by gwittel** [comment]
It doesn't seem like its needed.  I adjusted the version requirements in the gradle build and it compiled fine in Java 11.  I didn't try Java 8.  At least 11 would be better since its a long term supported release.
